name: tmdb_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.0.5
  cached_network_image: ^3.3.0
  rxdart: ^0.27.7
  awesome_dio_interceptor: ^1.0.0
  very_good_infinite_list: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
